name: arc_challenge
model_name: meta-llama/Llama-3.1-8B-Instruct
tasks: ["arc_challenge"]
limit: 100
num_fewshot: 5
batch_size: 8
device: cuda:0
seed: 42

results_file: results/arc/results_arc.json
output_dir: outputs/arc/
cache_dir: ./lm_cache