name: hella_swag
model_name: meta-llama/Llama-3.1-8B-Instruct
tasks: ["hellaswag"]
limit: 100
num_fewshot: 5
batch_size: 8
device: cuda:0
seed: 42

results_file: results/hellaswag/results_hellaswag.json
output_dir: outputs/hellaswag/
cache_dir: ./lm_cache